spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      url: jdbc:mysql://localhost:3306/fruit-shop?allowPublicKeyRetrieval=true&useSSL=false
      username: username
      password: Password@1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587